version       0.3
password      NUKyNCCLvgLH.
promote_date  on Saturday 8th December 2001 at 09:04pm
times         1152404641 2770 97 1009740417
levels        6 6 0 0 0
general       -1 0 0 1 1 0 0 16
user_set      1 0 0 99 1 1 0 0 0 0 1 0 #UNSET 0
user_ignores  0 0 0 0 0 0 0 0
purging       1 1155860641
last_site     atlantis reception
mail_verify   #UNSET
description   - remove this character
in_phrase     enters
out_phrase    goes
email         #UNSET
homepage      #UNSET
recap_name    Test
games         0 0 0 0 6 10 1012 3000
